GET http://localhost:5000/

###

POST http://localhost:5000/signin
Content-Type: application/json

{
  "email": "John@gmail.com",
  "password": "cookies"
}

###

GET http://localhost:5000/profile/124

###
POST http://localhost:5000/signin
Content-Type: application/json

{
  "email": "sarah@gmail.com",
  "password":"software",
}

###

POST http://localhost:5000/signup
Content-Type: application/json

{
  "name": "sally",
  "email": "sally2@gmail.com",
  "password":"cookies"
}
###

PUT http://localhost:5000/image
Content-Type: application/json

{
 "id":"8"
}

###

GET http://localhost:5000/profile/123

